'use strict';

const CONSTANTS = {
    RSTUDIO_INSTANCE: process.env.RSTUDIO_INSTANCE,
    ENVIRONMENT: process.env.ENVIRONMENT,
    //COGNITO_USER_POOL: process.env.COGNITO_USER_POOL,
    //COGNITO_USER_POOL_CLIENT: process.env.COGNITO_USER_POOL_CLIENT,
    COGNITO_USER_POOL: "$COGNITO_USER_POOL",
    COGNITO_USER_POOL_CLIENT: "$COGNITO_USER_POOL_CLIENT",
    CORS_ORIGIN: process.env.CORS_ORIGIN,
    BUCKET_NAME: process.env.BUCKET_NAME,
    DYNAMODB_FILES_GSI: process.env.DYNAMODB_FILES_GSI,
    DYNAMODB_FILES_TABLE: process.env.DYNAMODB_FILES_TABLE,
    DYNAMODB_JOBS_STATE_GSI: process.env.DYNAMODB_JOBS_STATE_GSI,
    DYNAMODB_JOBS_TIME_GSI: process.env.DYNAMODB_JOBS_TIME_GSI,
    DYNAMODB_JOBS_TABLE: process.env.DYNAMODB_JOBS_TABLE,
    DYNAMODB_SORT_STATUS_TYPE_GSI: process.env.DYNAMODB_SORT_STATUS_TYPE_GSI,
    DYNAMODB_SORT_GAMEID_TYPE_GSI: process.env.DYNAMODB_SORT_GAMEID_TYPE_GSI,
    DYNAMODB_SORT_CONNECTION_ID_TYPE_GSI: process.env.DYNAMODB_SORT_CONNECTION_ID_TYPE_GSI,
    DYNAMODB_TABLE: process.env.DYNAMODB_TABLE,
    DYNAMODB_OPTIONS: {},
    DYNAMODB_API_VERSION: process.env.DYNAMODB_API_VERSION,
    SQS_API_VERSION: process.env.SQS_API_VERSION,
    //SQS_MESSAGE_QUEUE_URL: process.env.SQS_MESSAGE_QUEUE_URL,
    SQS_MESSAGE_QUEUE_URL: "http://localhost:9324/queue/machination-backend-queue-dev.fifo",
    GLUE_JOB_NAME: process.env.GLUE_JOB_NAME,
    //KEYS_URL: process.env.KEYS_URL,
    KEYS_URL: "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-${PROJECT_KEY}/.well-known/jwks.json",
    SIGNED_URL_EXPIRE_SECONDS: 60 * 60,
    //WEBSOCKET_API_ENDPOINT: process.env.WEBSOCKET_API_ENDPOINT
    WEBSOCKET_API_ENDPOINT: "http://localhost:3001",
};

module.exports = CONSTANTS;
